using System.Collections;
using System.Collections.Generic;
using UnityEngine;
namespace Objects.Galaxy
{
    public class Names{
        
    public static StarNames starNames = new StarNames(); 
    public static PlanetNames planetNames = new PlanetNames();


    protected List<string> usedNames = new List<string>();
    protected List<string> names = new List<string>();

    public string getName(){
        if (names.Count > 0){
            var index = Random.Range(0,names.Count - 1);
            var name = names[index];
            names.RemoveAt(index);
            usedNames.Add(name);
            return name;
        }else{
            var temp = names;
            names = usedNames;
            usedNames = temp;
            return getName();
        }

    }

}
public class PlanetNames : Names{
    public PlanetNames(){
    names = new List<string>(){
"K-btransit","Kepler-btra","Kepler-btra","Kepler-btran","HDbradial","Kepler-btran","Kepler-btran","Kepler-btra","Kepler-btra","WASP-btran","Kepler-btran","Kepler-ctra","COROT-btra","Kepler-btran","Kepler-btran","Kepler-btra","HDbradial","Kepler-ctra","HDbradial","HDbradial","Kepler-dtra","Kepler-dtran","Kepler-ctran","Gliesecra","Kepler-btran","Kepler-ctra","HDbradial","Kepler-btra","Kepler-ctra","Kepler-btran","Kepler-btra","Kepler-btran","Kepler-btran","K-btransit","Kepler-btran","Kepler-btran","Kepler-btran","Kepler-btran","K-btransit","Kepler-dtra","Kepler-dtra","Kepler-btran","HATS-btran","Kepler-ctra","K-ctransit","Kepler-etra","Kepler-btra","HDAbradial","Kepler-btran","WASP-btran","Kepler-etra","Kepler-btran","Cancrifrad","WASP-btran","Kepler-btran","HDbradial","BetaUrsaeMinorisb","Kepler-btran","Kepler-btran","HDbradial","K-btransit","Kepler-btran","Kepler-btra","Kepler-etra","Kepler-ctra","HDbradial","Kepler-etra","Kepler-ctra","Kepler-btran","Kepler-ctran","WASP-btran","Kepler-btran","Kepler-btran","Kepler-ctran","Kepler-btran","WASP-btran","HDBbradial","Kepler-btran","HDcradial","Kepler-btran","Kepler-btran","Qatar-btra","WASP-btran","PsiDraconisBb","Kepler-btran","Kepler-btran","Kepler-btran","Kepler-btran","Kepler-btran","Kepler-btra","Kepler-btran","Kepler-btr","K-btransit","HDbradial","K-btransit","Kepler-btra","Kepler-ftra","HDbradialv","Kepler-btra","Kepler-btran","Kepler-dtra","Kepler-btran","Kepler-dtran","Kepler-btran","Kepler-btran","MuAraebra","HDcradial","HDbradial","HDbradial","Kepler-dtra","Kepler-btran","Kepler-btran","Kepler-btran","HDbradial","MOA--BLG-Lbm","HATS-btran","Kepler-btran","HDdradial","Kepler-btran","Kepler-btra","Kepler-btran","BD+bradia","Kepler-btran","Kepler-btra","HDbradial","Kepler-btra","Kepler-ctra","HDbradial","Kepler-ctra","Kepler-dtra","Kepler-ctra","HDbradial","HATS-btran","HIPbradia","Kepler-ctra","Kepler-ctra","Kepler-btran","Kepler-btra","UZFornacisc","Kepler-dtra","Kepler-btran","KICctransi","Kepler-ctra","Kepler-ctra","Herculisb","Kepler-btran","Kepler-btran","K-btransit","Kepler-dtran","Kepler-btran","Kepler-btran","Kepler-btran","Kepler-btra","HAT-P-btra","Kepler-btran","Kepler-dtra","Kepler-btra","Kepler-btra","Kepler-btran","HDbradial","WASP-btran","Kepler-btran","Kepler-dtra","Kepler-btran","Kepler-dtra","Kepler-btr","KICbimaging","Kepler-btran","HDbradial","Kepler-ctra","OGLE-TR-bt","Kepler-ctra","WASP-btran","Kepler-btran","Kepler-btran","Kepler-btran","Kepler-ctran","Kepler-btran","Virginisb","Kepler-etra","Kepler-btra","HRbimaging","UpsilonAndromedaeb","Kepler-btr","Kepler-dtra","Kepler-btr","K-btransit","COROT-btra","HATS-btran","HDbradial","Kepler-ctra","K-btransit","Kepler-btra","Kepler-btran","Kepler-ctran","OGLE--BLG-Lb","HDcradial","HDcradia","Kepler-ctra","Kepler-btran"
        };
    }
}
public class StarNames : Names{
    public StarNames(){
    names = new List<string>(){
"ACHERNAR",
"Achird",
"ACRUX",
"Acubens",
"ADARA",
"Adhafera",
"Adhil",
"AGENA",
"Ain al Rami",
"Ain",
"Al Anz",
"Al Kalb al Rai",
"Al Minliar al Asad",
"Al Minliar al Shuja",
"Aladfar",
"Alathfar",
"Albaldah",
"Albali",
"ALBIREO",
"Alchiba",
"ALCOR",
"ALCYONE",
"ALDEBARAN",
"ALDERAMIN",
"Aldhibah",
"Alfecca Meridiana",
"Alfirk",
"ALGENIB",
"ALGIEBA",
"ALGOL",
"Algorab",
"ALHENA",
"ALIOTH",
"ALKAID",
"Alkalurops",
"Alkes",
"Alkurhah",
"ALMAAK",
"ALNAIR",
"ALNATH",
"ALNILAM",
"ALNITAK",
"Alniyat",
"Alniyat",
"ALPHARD",
"ALPHEKKA",
"ALPHERATZ",
"Alrai",
"Alrisha",
"Alsafi",
"Alsciaukat",
"ALSHAIN",
"Alshat",
"Alsuhail",
"ALTAIR",
"Altarf",
"Alterf",
"Aludra",
"Alula Australis",
"Alula Borealis",
"Alya",
"Alzirr",
"Ancha",
"Angetenar",
"ANKAA",
"Anser",
"ANTARES",
"ARCTURUS",
"Arkab Posterior",
"Arkab Prior",
"ARNEB",
"Arrakis",
"Ascella",
"Asellus Australis",
"Asellus Borealis",
"Asellus Primus",
"Asellus Secondus",
"Asellus Tertius",
"Asterope",
"Atik",
"Atlas",
"Auva",
"Avior",
"Azelfafage",
"Azha",
"Azmidiske",
"Baham",
"Baten Kaitos",
"Becrux",
"Beid",
"BELLATRIX",
"BETELGEUSE",
"Botein",
"Brachium",
"CANOPUS",
"CAPELLA",
"Caph",
"CASTOR",
"Cebalrai",
"Celaeno",
"Chara",
"Chort",
"COR CAROLI",
"Cursa",
"Dabih",
"Deneb Algedi",
"Deneb Dulfim",
"Deneb el Okab",
"Deneb el Okab",
"Deneb Kaitos Shemali",
"DENEB",
"DENEBOLA",
"Dheneb",
"Diadem",
"DIPHDA",
"Dschubba",
"Dsiban",
"DUBHE",
"Ed Asich",
"Electra",
"ELNATH",
"ENIF",
"ETAMIN",
"FOMALHAUT",
"Fornacis",
"Fum al Samakah",
"Furud",
"Gacrux",
"Gianfar",
"Gienah Cygni",
"Gienah Ghurab",
"Gomeisa",
"Gorgonea Quarta",
"Gorgonea Secunda",
"Gorgonea Tertia",
"Graffias",
"Grafias",
"Grumium",
"HADAR",
"Haedi",
"HAMAL",
"Hassaleh",
"Head of Hydrus",
"Herschel's",
"Heze",
"Hoedus II",
"Homam",
"Hyadum I",
"Hyadum II",
"IZAR",
"Jabbah",
"Kaffaljidhma",
"Kajam",
"KAUS AUSTRALIS",
"Kaus Borealis",
"Kaus Meridionalis",
"Keid",
"Kitalpha",
"KOCAB",
"Kornephoros",
"Kraz",
"Kuma",
"Lesath",
"Maasym",
"Maia",
"Marfak",
"Marfak",
"Marfic",
"Marfik",
"MARKAB",
"Matar",
"Mebsuta",
"MEGREZ",
"Meissa",
"Mekbuda",
"Menkalinan",
"MENKAR",
"Menkar",
"Menkent",
"Menkib",
"MERAK",
"Merga",
"Merope",
"Mesarthim",
"Metallah",
"Miaplacidus",
"Minkar",
"MINTAKA",
"MIRA",
"MIRACH",
"Miram",
"MIRPHAK",
"MIZAR",
"Mufrid",
"Muliphen",
"Murzim",
"Muscida",
"Muscida",
"Muscida",
"Nair al Saif",
"Naos",
"Nash",
"Nashira",
"Nekkar",
"NIHAL",
"Nodus Secundus",
"NUNKI",
"Nusakan",
"Peacock",
"PHAD",
"Phaet",
"Pherkad Minor",
"Pherkad",
"Pleione",
"Polaris Australis",
"POLARIS",
"POLLUX",
"Porrima",
"Praecipua",
"Prima Giedi",
"PROCYON",
"Propus",
"Propus",
"Propus",
"Rana",
"Ras Elased Australis",
"Ras Elased Borealis",
"RASALGETHI",
"RASALHAGUE",
"Rastaban",
"REGULUS",
"Rigel Kentaurus",
"RIGEL",
"Rijl al Awwa",
"Rotanev",
"Ruchba",
"Ruchbah",
"Rukbat",
"Sabik",
"Sadalachbia",
"SADALMELIK",
"Sadalsuud",
"Sadr",
"SAIPH",
"Salm",
"Sargas",
"Sarin",
"Sceptrum",
"SCHEAT",
"Secunda Giedi",
"Segin",
"Seginus",
"Sham",
"Sharatan",
"SHAULA",
"SHEDIR",
"Sheliak",
"SIRIUS",
"Situla",
"Skat",
"SPICA",
"Sterope II",
"Sualocin",
"Subra",
"Suhail al Muhlif",
"Sulafat",
"Syrma",
"Tabit (1543)",
"Tabit (1544)",
"Tabit (1552)",
"Tabit (1570)",
"Talitha",
"Tania Australis",
"Tania Borealis",
"TARAZED",
"Taygeta",
"Tegmen",
"Tejat Posterior",
"Terebellum",
"Terebellum",
"Terebellum",
"Terebellum",
"Thabit",
"Theemim",
"THUBAN",
"Torcularis Septentrionalis",
"Turais",
"Tyl",
"UNUKALHAI",
"VEGA",
"VINDEMIATRIX",
"Wasat",
"Wezen",
"Wezn",
"Yed Posterior",
"Yed Prior",
"Yildun",
"Zaniah",
"Zaurak",
"Zavijah",
"Zibal",
"Zosma",
"Zuben Elschemali",
"Zuben Elakrab",
    };
}
}
}